### ISSUE TITLE
Saving Settings

### ISSUE THREAD

**Issue by Feary** [erupt321/curtracker#4]
I see there are two locations for settings. the first one is in the file settings.xml and the second is character name.xml in the settings folder.

**Comment by erupt321** [comment]
Technically this is not a bug, the texts window is created in the global space before login, otherwise there are some issues with the config addon.  Now on login I do reload config settings and since at the point in time I now have a character name this is the time I start using the information in the character specific file.  Otherwise the settings.xml settings get used as a default backup.
